# fly.toml app configuration file generated for JobAutoApply

app = "job-automation-app"
primary_region = "ord"

[build]

[env]
JSEARCH_API_KEY = "9bba5132c8msh952c6232f921359p1231e9jsn02b582e9bf63"

[[services]]
internal_port = 8080
processes = ["app"]

  [services.http_checks]
  enabled = true
  interval = 10000
  timeout = 5000
  grace_period = "5s"
  method = "get"
  path = "/api/ping"
